#!/bin/sh
# deps: curl, jq, wget, ffmpeg, seq, paste
set -e

#OPTIONS
TMP_PATH="/tmp/"
OUTPUT_BITRATE="320k" # Max (=default = 360k)
OUTPUT_FORMAT="${2:=opus}" # (default = opus);
USER_AGENT_HEADER="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"
# OUTPUT_FORMAT="mp3" # uncomment for mp3

query="$1"
query="$(echo "$query " | tr ' ' '+')"

songs_list="$(curl --silent -H "$USER_AGENT_HEADER"\
        "https://www.jiosaavn.com/api.php?p=1&q=$query&_format=json&_marker=0&api_version=4&ctx=wap6dot0&n=10&__call=search.getResults" )"

# list_id="$(echo "$songs_list" | jq -r '.results[].more_info.artistMap.primary_artists[0].name')"

echo "$songs_list" | jq -r '.results[].more_info.artistMap.primary_artists[0].name' > "$TMP_PATH/fmd.1"
echo "$songs_list" | jq -r '.results[].title' > "$TMP_PATH/fmd.2"
echo "$songs_list" | jq -r '.results[].year' > "$TMP_PATH/fmd.4"
list_legth="$(wc -l "$TMP_PATH/fmd.1")"
seq 1 "${list_legth%% *}" > "$TMP_PATH/fmd.3"

paste "$TMP_PATH/fmd.3" "$TMP_PATH/fmd.1" "$TMP_PATH/fmd.2" "$TMP_PATH/fmd.4"

echo ""
echo "Select:" ; read -r sel_idx
song="$(echo "$songs_list" | jq ".results[$((sel_idx - 1))]")"

song_title="$(echo "$song" | jq -r '."title"')"
song_artist="$(echo "$song" | jq -r '."more_info"."artistMap"."primary_artists"[0].name')"
song_album="$(echo "$song" | jq -r '."more_info"."album"')"
song_label="$(echo "$song" | jq -r '."more_info"."label"')"
song_year="$(echo "$song" | jq -r '."year"')"
song_cprtxt="$(echo "$song" | jq -r '."more_info"."copyright_text"')"

# match song
song_id="$(echo "$song" |  jq -r '.id')"
song_url="$(curl --silent -H "$USER_AGENT_HEADER"\
        "https://www.jiosaavn.com/api.php?__call=song.getDetails&cc=in&_marker=0%3F_marker%3D0&_format=json&pids=$song_id" \
        | jq -r ".\"$song_id\".\"media_preview_url\"")"

# parse song_url
song_url="https://aac.${song_url#http*preview.}"
song_url="${song_url%_96_p.mp4}_320.mp4"

filename="$(echo "$song_title-$song_artist($song_year)" | tr ' ' '_')"

wget --show-progress -q "$song_url" -O "$filename.tmp" > /dev/null

printf "Extracting Audio..."

[ -f "$filename.opus" ] && rm "$filename.opus"

ffmpeg -i "$filename.tmp" -metadata artist="$song_artist" \
        -b:a "$OUTPUT_BITRATE" \
        -metadata album="$song_album" -metadata downloaded-using="free-music-downloader[FMD] by Liupold." \
        -metadata title="$song_title" -metadata year="$song_year" \
        -metadata label="$song_label" -metadata copyright="$song_cprtxt" "$filename.$OUTPUT_FORMAT" >/dev/null 2>&1\
&& rm "$filename.tmp"
echo 'done'
exit 0 # Everyting went well.

