name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '0 1 1,14,28 * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install req. packages
      run: sh -c "sudo apt install ffmpeg findutils"

    - name: sample download (default)
      run: echo "1" | sh ./fmd "" && [ -n "$(find -name '*.mp3')" ]

    - name: sample download (opus)
      run: echo "1" | sh ./fmd "" opus && [ -n "$(find -name '*.opus')" ]

